name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment (required for Android and SonarQube)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      # Step 3: Install Klint
      - name: Install Klint
        run: |
          curl -sSLO https://secure-web.cisco.com/1Horo29Lb7-DwnTEgUHq7fRnkBl2lGzt9Twh4fMuExSMk-DMthq2pT0dNfVPjJhu02tcKHlSn7Eqk3XPyi4axoGSyn4R7KZGfM5GO3hK4zAkkOfswAd2QLl_UsF_IJT0j9fsTEd0ZLvxsYpLhwlrGNjt3VC5aAL0sN7FQxL8C5bYoC8o3seWmow8wCxM3tOgoVullPo6xc481L0zulxrGzThqIYOfsMNofJY_ZzZ6SJLbitfnxCpNUxe_2FgvddRd7jizFTyMvThpS-0MWRpGNxs8XOKdBk4YSA_nZIHQD1odY10oObe8DGJZVGblUxSJ9jg0I20CBDQC04qsbGwStGLbwbLrzHEdqfKOXnVs-apAuULUyliMiXY3OypdwY8jCDzgh_nXd8SADYkTPFaoKKvNaPcOeFqluJJjPgMnTTWVHVe7UwwcalfE3f1GvBMIiiVIja_b1Ic-RbeMIM7P3WeAA3Z5dsDEh9TNHfcEc43loP8e0yl4INDu4mBBxJJPjFAYxo52SMNkq36p1M8S-Q/https%3A%2F%2Fgithub.com%2Fpinterest%2Fktlint%2Freleases%2Fdownload%2F0.50.0%2Fktlint && chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      # Step 4: Run Klint for Kotlin code quality
      - name: Run Klint
        run: |
          ./gradlew ktlintCheck

      # Step 5: Set up SonarQube Scanner
      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization_key
            -Dsonar.host.url=https://secure-web.cisco.com/1eL3G9oR4wjxz498fdPxu73qj6K9p3YgtQDxVcXVynN02r-Zth5OscWlWMaYwe7JChOCOvLo-bevdxBNDns6ADz0OYasAJ4X6-WFKIzXtoE7DAGTdjUYgE54JvgTNz2Lbs7elxMpEVGqgm11i225KTyHzKjpoLs9-_yYnufLbqsbAS50PTh8QwOiSlr-4-Whokvru81vdGrHZZp2k3E_x4WGDP7PlO-B2N3JBTHUtm0jFuTRRAiNiIaqdT5bW-u8QrAyNR0MVEM04gzEIrWh1AC8kY2O0SF27-niu-1C2xv3Qp-syuP85Z4vNAlxsuhZiphpzjBdZYW_EGd2o_NPm5K0wNxx_-kKYpYxTtuG4F04H9GGr0H-gE2g8mJoni3swRtXe-KeY5Txs5ZPEt3-qW5WOosRiKQSuhwCJb-fZHw-GcAhzJ-W518DJmCQRcsNuZwJWNRVrX98GVOeaWGgRPgP3trtAq7Ojy1FXB05P3z-BpDHGWU291qg4XsOb0b07QYL8_ZpZUOICCgIcBau66Q/https%3A%2F%2Fsonarcloud.io
            -Dsonar.sources=.

      # Step 6: Run SonarQube Analysis
      - name: Run SonarQube Scanner
        run: |
          sonar-scanner
